FROM node:16.17.0-alpine
WORKDIR /usr/node-app
COPY package.json ./
COPY tsconfig.json ./
COPY babel.config.js ./
COPY src ./src
RUN ls -a
RUN yarn
RUN yarn build
## this is stage two , where the app actually runs
FROM node:16.17.0-alpine
WORKDIR /usr/node-app
COPY package.json ./
RUN yarn --only=production
COPY --from=0 /usr/node-app/dist .
RUN yarn global add pm2
EXPOSE 3000
CMD ["pm2-runtime","server.js"]